import type { Metadata, Viewport } from 'next'

import { Toaster } from 'sonner';
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

import { Ubuntu } from 'next/font/google';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ubuntu',
  weight: ['300', '400', '500', '700']
});

export const metadata: Metadata = {
  title: 'MotionSchool',
  description: 'Generated by Aman',
  manifest:"/manifest.json",


}
export const viewport: Viewport = {
  themeColor: "#4f46e5",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={ubuntu.className}>
        <main>{children}</main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
    </ClerkProvider>
  )
}
